#!/usr/bin/python3
 # Raise a NameError with the provided message
def raise_exception_msg(message=""):
                                                     
            raise NameError(message)

                                                 
                
                                                                          
                              
                                                   
            
